mobiusml/aana_sdk

aana/configs/settings.py
aana/core/models/base.py
aana/core/models/chat.py
aana/deployments/hf_blip2_deployment.py
aana/deployments/hf_pipeline_deployment.py
aana/deployments/hf_text_generation_deployment.py
aana/deployments/idefics_2_deployment.py
aana/deployments/sentence_transformer_deployment.py
aana/deployments/vad_deployment.py
aana/deployments/vllm_deployment.py
aana/deployments/whisper_deployment.py

**Summary**
This pull request addresses the issue of warnings generated by Pydantic when using field names that conflict with Pydantic's protected namespaces. Specifically, warnings like the following were observed:
```
/root/.cache/pypoetry/virtualenvs/aana-vIr3-B0u-py3.10/lib/python3.10/site-packages/pydantic/_internal/_fields.py:161: 
UserWarning: Field "model_dir" has a conflict with protected namespace "model_".
```
**Key Changes**:
- Compiled a list of protected field names (`pydantic_protected_fields`).
- Integrated this list into the model configuration by redefining the `protected_namespaces` in the `ConfigDict` as follows:
```python
model_config = ConfigDict(protected_namespaces=(*pydantic_protected_fields,))
```
This is a workaround to prevent warnings caused by naming …

Updated Pydantic Model Configurations for Protected Fields

---

.devcontainer/Dockerfile

Fix for:
The tests for postgres db are failing when running directly via command line in the devcontainer
Key changes:
- Adding locale in and set it inside devcontainer dockerfile

fix for locale

---

aana/api/request_handler.py
aana/core/models/api.py
aana/sdk.py
aana/tests/conftest.py
aana/tests/units/test_app_deploy.py
aana/tests/units/test_status_endpoint.py

This update introduces a new status endpoint to the SDK for monitoring status. It also includes additional tests for both the new endpoint and previously implemented functionality.
1. **Status Endpoint**: Added a new endpoint that returns the SDK status, improving system monitoring capabilities.
2. **Status Endpoint Tests**: Implemented tests to ensure the proper functioning of the new status endpoint.
3. **Deploy Error Tests**: Added missing tests for deploy error handling, originally intended for PR #148.
Closes https://github.com/mobiusml/aana_sdk/issues/162

Status Endpoint

---

aana/core/models/chat.py
aana/core/models/sampling.py
aana/deployments/hf_text_generation_deployment.py
aana/deployments/idefics_2_deployment.py
aana/deployments/vllm_deployment.py
aana/tests/deployments/test_idefics2_deployment.py
aana/tests/deployments/test_text_generation_deployment.py
aana/tests/units/test_sampling_params.py

**Summary:**
This update introduces new parameters to the `SamplingParams` class, allowing for more flexible and customizable behavior when using vLLM and Hugging Face (HF) transformers based text generation deployments.
**Key Changes:**
1. **`repetition_penalty` Parameter**: Added a new parameter, `repetition_penalty` that is supported by both vLLM and HF transformers.
2. **`kwargs` Parameter**: Introduced `kwargs` to pass extra parameters that are not directly implemented in `SamplingParams`. These will be forwarded to the `SamplingParams` of vLLM and the generation parameters of HF transformers, enhancing flexibility.
Closes: https://github.com/mobiusml/aana_sdk/issues/171

Add `repetition_penalty` and `kwargs` parameters to `SamplingParams`

---

.github/workflows/run_tests_with_gpu.yml
pg_ctl.sh
test_volume.dstack.yml
tests.dstack.yml

**Summary:**  
This pull request introduces a new workflow for running tests with GPU support using dstack.
**Key Changes:**
1. **New GitHub Actions Workflow**: Added a workflow file `.github/workflows/run_tests_with_gpu.yml` to run tests with GPU support. 
2. **dstack Test Configuration**: Added `tests.dstack.yml` to configure the testing environment and run tests using dstack.
Closes: https://github.com/mobiusml/aana_sdk/issues/81

Run Tests with GPU

---

aana/deployments/task_queue_deployment.py
aana/storage/op.py
aana/storage/repository/task.py
aana/tests/db/datastore/test_task_repo.py

This Pull Request enhances the TaskQueueDeployment to support multiple concurrent instances. It introduces mechanisms to avoid race conditions during task allocation and processing.
Closes: https://github.com/mobiusml/aana_sdk/issues/186

Support for Multiple Instances of TaskQueueDeployment

---

aana/deployments/base_deployment.py
aana/deployments/base_text_generation_deployment.py
aana/deployments/haystack_component_deployment.py
aana/deployments/hf_blip2_deployment.py
aana/deployments/hf_pipeline_deployment.py
aana/deployments/hf_text_generation_deployment.py
aana/deployments/idefics_2_deployment.py
aana/deployments/pyannote_speaker_diarization_deployment.py
aana/deployments/sentence_transformer_deployment.py
aana/deployments/vad_deployment.py
aana/deployments/vllm_deployment.py
aana/deployments/whisper_deployment.py
aana/tests/units/test_deployment_restart.py

**Summary:**  
This PR introduces an automatic health check and restart mechanism for deployments, addressing an issue where deployments returned errors but were not terminated, preventing automatic recovery by Ray.
**Key Changes:**
1. **Exception-Based Health Check:** Added a decorator, `exception_handler`, which logs exceptions to monitor deployment health and helps trigger restarts if necessary.
2. **Automatic Restart Logic:** Deployments will now restart if more than 50% of requests fail, ensuring service stability.
3. **Tests:** Added tests to verify deployment restart functionality following consecutive failures.

Deployment Health Check and Automatic Restart

---

aana/deployments/aana_deployment_handle.py
aana/tests/units/test_deployment_retry.py
aana/utils/core.py

**Summary:**
This PR implements retry logic to ensure deployment requests are retried upon failure, addressing the issue of one-time request attempts that do not retry on failure.
**Key Changes:**
1. **Retry Logic Added to Deployment Requests**: Introduced a retry mechanism with configurable parameters such as the number of retries, delay between retries, and specific exceptions that can trigger a retry.
2. **Exponential Backoff with Jitter**: Integrated `sleep_exponential_backoff` for delays between retries, applying full jitter to reduce the chances of synchronized retry requests.
3. **Tests for Retry Mechanism**: Added unit tests to validate the retry functionality.

Retry Mechanism for Deployment Requests

---

.github/workflows/run_tests_with_gpu.yml

This PR adds an extra step that extracts pytest logs from the full dstack logs so it's easier to review it.
Also, dstack got an update that fixes the disconnection issue when running in GitHub Actions that I reported. So now GPU tests are fully operational.
Example run: https://github.com/mobiusml/aana_sdk/actions/runs/11594576389/job/32281142696#step:7:1

Fixes for GPU Tests with dstack

---

aana/sdk.py
aana/utils/core.py

This pull request includes changes to improve the robustness and reliability of Aana SDK by updating retryable exceptions and preventing overflow in exponential backoff calculations.
* [`aana/sdk.py`](diffhunk://#diff-9894ea7f31916f877102b6d32121e6a4a41dddd12ef41d0233e5888822df8a08L48-R60): Updated the default list of retryable exceptions to include `ActorDiedError` and `OutOfMemoryError` in addition to `InferenceException`.
* [`aana/utils/core.py`](diffhunk://#diff-d4c034f8f14433299472b4070e731a3e3f3bc3215daa08a3b9b147c6f6ebed6dL96-R98): Modified the `sleep_exponential_backoff` function to cap the number of attempts at 32 to prevent overflow issues.

Update Retryable Exceptions

---

aana/api/request_handler.py
aana/deployments/pyannote_speaker_diarization_deployment.py
aana/deployments/vad_deployment.py
aana/deployments/whisper_deployment.py

By default, Ray tries to check the health of the Ray deployment every 10 seconds (health_check_period_s) and if the health check doesn't happen within 30 seconds (health_check_timeout_s), Ray will consider the deployment unhealthy. After 3 consecutive health check failures (or timeouts), Ray will restart the deployment.
The checks are executed asynchronously. But if the deployment runs a blocking operation, the health check will be delayed and can timeout. This can lead to cases where the deployment is healthy, just slow and blocked by a long-running operation but Ray will consider it unhealthy and restart it.
To address this issue, we can add `await asyncio.sleep(0)` in the long-running operation where we want to yield control back to the event loop. This is what I've done in the whisper …

Mitigate Health Check Timeouts for Blocking Operations in Deployments

---

aana/storage/repository/task.py
aana/tests/db/datastore/test_task_repo.py

Update all datetime instances to use UTC, ensuring consistent time handling throughout the task repository.

Use Timezone Consistently in Task Repository

---

aana/sdk.py
poetry.lock

Eliminate the use of the `route_prefix` in deployment options  as it is no longer supported.

Removed deprecated route_prefix from Deployment Options

---

aana/deployments/whisper_deployment.py

Improved error handling by wrapping the segment processing loop in a try-except block to catch inference errors.

Improved Error Handling in WhisperDeployment

---

aana/sdk.py

Introduce parameters for dashboard host and port in the AanaSDK initialization to enhance configuration options for the dashboard server.

Add Ray Dashboard Host and Port Parameters

---

aana/cli.py
aana/sdk.py

Introduce command-line options to specify the Ray dashboard's address and port for Aana CLI.

Add Ray Dashboard Host and Port Parameters in Aana CLI

---

aana/deployments/vllm_deployment.py
aana/deployments/whisper_deployment.py

Incorporate torch cache clearing into the health check to prevent GPU memory leaks in vLLM and Whisper deployments.
Issue: https://github.com/mobiusml/aana_episodic_retrieval/issues/17

Add Torch Cache Clearing to Health Check for vLLM and Whisper Deployments

---

aana/configs/settings.py
aana/tests/units/test_settings.py

Update the Settings class to automatically configure temporary directories based on the specified `tmp_data_dir`, ensuring that dependent paths are set correctly if not explicitly provided.

Refactor Settings to Dynamically Set Temporary Directories

---

README.md
aana/api/api_generation.py
aana/core/models/image.py
aana/core/models/video.py
aana/exceptions/runtime.py
aana/tests/units/test_api_generation.py
aana/tests/units/test_app_upload.py
aana/tests/units/test_image_input.py
aana/tests/units/test_video_input.py
aana/utils/json.py
docs/index.md

Refactor file upload to allow reference uploaded files. That streamlines file uploading functionality and allows more flexible use of file uploads Update the documentation to include examples for API requests involving structured and binary data.

Refactor File Uploads

---

.github/workflows/python-package.yml
aana/deployments/vad_deployment.py
aana/tests/deployments/test_vad_deployment.py

The current model path is moved out from the  S3 location, so it is wiser to use the same pyannote VAD model available in HF repo.
-Changes in deployment and test files
-Changes in Git workflow to add HF_TOKEN

Update VAD model in VAD deployment

---

aana/api/api_generation.py
aana/api/app.py
aana/configs/settings.py
aana/core/models/api_service.py
aana/exceptions/api_service.py
aana/storage/models/api_key.py
poetry.lock
pyproject.toml

Introduce middleware for API key validation and integrate LAGO API service for usage tracking.
How to use API service in your Aana Application:
1. Enable API service by setting the environment variable API_SERVICE__ENABLED=True.
2. Set API_SERVICE__LAGO_URL and API_SERVICE__LAGO_API_KEY environment variables if you want to send usage events to Lago.
3. Add the ApiKeyType parameter to the run method of the endpoint that you want to track usage for or if you need API key information (e.g., to implement multi-tenancy).
4. Send usage events using the send_usage_event method of the endpoint class.
```python
from aana.api.api_generation import Endpoint
from aana.core.models.api_service import ApiKeyType
class SearchEndpoint(Endpoint):
async def run(self, query: str, collection: str, api_key: …
```

Implement API key validation and LAGO API integration

---

aana/api/api_generation.py
aana/api/app.py
aana/api/request_handler.py
aana/api/security.py
aana/configs/settings.py
aana/exceptions/api_service.py
aana/sdk.py
aana/storage/models/api_key.py
docs/pages/openai_api.md

- Improved API key validation with better error handling
- Introduced admin access requirements for certain endpoints
- Introduced two new options for user-defined endpoints:
- `admin_required`: Flag indicating if the endpoint requires admin access.
- `always_defer`: Flag indicating if the endpoint should always defer execution to the task queue.
- Added configuration options for enabling or disabling the OpenAI-compatible chat endpoint.

Enhance API Key Validation and Admin Access Control

---

aana/api/security.py

Introduce an `IsAdminDependency` to check if user have admin rights in the endpoints.

Add is_admin Dependency

---

aana/api/exception_handler.py
aana/configs/settings.py

- Fix the validation exception handler to exclude context in error data to prevent serialization issues.
- Introduce a configuration option to control the inclusion of stacktrace in error messages to prevent leaks of implementation details.

Fix Validation Error Bug and Add Option to Disable Stacktrace in Error Messages

---

aana/api/exception_handler.py
aana/core/models/media.py
aana/tests/units/test_media_id.py

Remove unnecessary context from validation error messages and streamline the media ID validation logic for clarity and efficiency.

Fix Validation Error Handler

---

aana/api/app.py

Update the API key check middleware to exclude the OPTIONS method from validation, allowing preflight requests to pass through without triggering the API key check.

Exclude OPTIONS method in API key check middleware

---

aana/api/api_generation.py
aana/api/responses.py
aana/routers/openai.py
aana/utils/openapi.py
aana/utils/openapi_code_templates/python_form_streaming.j2

- Replace references to ndjson with concatenated JSON (application/json-seq) as it is the correct response type.
- Update python snippets for the streaming endpoints in the docs.

Replace references to ndjson with concatenated JSON

---

aana/configs/settings.py
aana/deployments/base_deployment.py
aana/deployments/gpu_manager.py
aana/deployments/haystack_component_deployment.py
aana/integrations/haystack/remote_haystack_component.py
aana/sdk.py
aana/tests/integration/test_haystack_remote_component.py
notebooks/haystack_integration.ipynb
notebooks/rag.ipynb

- Introduce an experimental GPU manager enhancing GPU resource allocation.
- Move RemoteHaystackComponent to a separate file.
- Update import paths in tests and notebooks to align with the new structure.
The GPU manager is an experimental feature designed to enhance the GPU allocation for multi GPU instances with GPU sharing.
Currently, Ray supports GPU sharing (partial GPU allocation) but the replicas of the same deployment are often allocated to the same GPU. This can lead to inefficient resource utilization where some GPUs are fully utilized while others are idle.
From my research, there is no way to enforce that replicas of the same deployment are allocated to different GPUs (if possible). I've tried some workarounds using Ray's placement groups, but they require monkey patching the …

Introduce GPU Manager

---

aana/api/app.py
aana/api/exception_handler.py

Implement CORS handling in custom exception handlers to ensure proper CORS headers are included for error.
CORS middleware and custom exception handlers don't work well together. CORS middleware is skipped and headers are not added.
The official solution is to wrap the entire application with CORSMiddleware. But in our case it's not possible because we use Ray and it expects FastAPI app, not CORSMiddleware.
See https://github.com/fastapi/fastapi/discussions/8027 for more info.

Add CORS Handling to Exception Handlers

---

aana/api/app.py
aana/api/request_handler.py

Improve the logic of the readiness check endpoint `/api/ready`.

Refactor Readiness Check Endpoint
